version: '3.8'
services:
  backend:
    build: .
    ports:
      - "3000:3000"
    env_file: .env
    restart: unless-stopped
    command: >
      sh -c "npx prisma generate &&
             npx prisma migrate deploy &&
             node dist/index.js"
