FROM node:20

WORKDIR /src

# Installe les dépendances
COPY package*.json ./
RUN npm install

# Copie le code
COPY . .

# Build TypeScript
RUN npm run build

# Expose ton port (à adapter si besoin)
EXPOSE 3000

# Lance l'app (pense à utiliser le build js)
CMD ["node", "dist/index.js"]
