import type { Metadata } from "next";
import Navbar from "./components/Navbar";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fr">
      <body className="antialiased flex flex-col h-screen">
        <Navbar />
        {/* Le main devient flex-1 pour remplir le reste */}
        <main className="flex-1">{children}</main>
      </body>
    </html>
  );
}
